function Loading() {
	return <div>Loading ...
		<p className="bg-bug invisible">test</p>
		<p className="bg-bugbg invisible">test</p>
		<p className="bg-dark invisible">test</p>
		<p className="bg-darkbg invisible">test</p>
		<p className="bg-dragon invisible">test</p>
		<p className="bg-dragonbg invisible">test</p>
		<p className="bg-electric invisible">test</p>
		<p className="bg-electricbg invisible">test</p>
		<p className="bg-fairy invisible">test</p>
		<p className="bg-fairybg invisible">test</p>
		<p className="bg-fighting invisible">test</p>
		<p className="bg-fightingbg invisible">test</p>
		<p className="bg-fire invisible">test</p>
		<p className="bg-firebg invisible">test</p>
		<p className="bg-flying invisible">test</p>
		<p className="bg-flyingbg invisible">test</p>
		<p className="bg-ghost invisible">test</p>
		<p className="bg-ghostbg invisible">test</p>
		<p className="bg-grass invisible">test</p>
		<p className="bg-grassbg invisible">test</p>
		<p className="bg-ground invisible">test</p>
		<p className="bg-ice invisible">test</p>
		<p className="bg-icebg invisible">test</p>
		<p className="bg-normal invisible">test</p>
		<p className="bg-normalbg invisible">test</p>
		<p className="bg-poison invisible">test</p>
		<p className="bg-poisonbg invisible">test</p>
		<p className="bg-psychic invisible">test</p>
		<p className="bg-psychicbg invisible">test</p>
		<p className="bg-rock invisible">test</p>
		<p className="bg-rockbg invisible">test</p>
		<p className="bg-steel invisible">test</p>
		<p className="bg-steelbg invisible">test</p>
		<p className="bg-water invisible">test</p>
		<p className="bg-waterbg invisible">test</p>
	</div>
}
export default Loading
